export const LANGUAGE_OPTIONS = [
  { value: 'Vietnamese', label: 'Tiếng Việt' },
  { value: 'English', label: 'English' },
  { value: 'Japanese', label: 'Japanese' },
  { value: 'Korean', label: 'Korean' },
  { value: 'Spanish', label: 'Spanish' },
  { value: 'Arabic', label: 'Arabic' },
  { value: 'French', label: 'French' },
  { value: 'Portuguese', label: 'Portuguese' },
  { value: 'Chinese', label: 'Chinese' },
];

export const AUDIENCE_OPTIONS = [
  { value: 'viet', label: 'View Việt' },
  { value: 'foreign', label: 'View Ngoại' },
];

export const TOPIC_SUGGESTIONS = [
  "Sinh tồn hoang dã",
  "Mukbang AI",
  "Cuộc chiến động vật",
  "Khám phá không gian",
  "Pokémon đời thực",
  "Vũ trụ đa chiều",
  "Cuộc sống thời tiền sử",
  "Trí tuệ nhân tạo vs. Con người",
  "Thế giới tương lai năm 3000",
  "Robot chiếm lĩnh Trái Đất",
  "Review các món ăn \"tương lai\"",
  "Thú cưng nói chuyện bằng AI",
  "Khủng long trở lại trái đất",
  "Zombie đại chiến",
  "Dạy mèo/cún cách nói tiếng người",
  "Chuyển kiếp – hành trình linh hồn",
  "Thế giới tí hon",
  "Tòa nhà 3D xây bằng AI",
  "Người ngoài hành tinh ghé thăm trái đất",
  "Giải phẫu ảo – cơ thể người từ bên trong",
  "Tạo cảnh 3D mê cung khổng lồ",
  "Xây đảo riêng sống 1 mình",
  "Hướng dẫn tạo doanh nghiệp ảo trong 5 phút",
  "Kể chuyện triết lý kiểu “Stoic Life”",
  "Tạo video thả thư vào vũ trụ",
  "Bình luận phim bom tấn bằng nhân vật AI",
  "Quái vật truyền thuyết xuất hiện ngoài đời",
  "Hành tinh chỉ toàn mèo/cún",
  "Cuộc sống giữa lòng núi lửa",
  "Trí tuệ cổ xưa bật mí bí mật",
  "Hướng dẫn học tiếng Anh với hoạt hình AI",
  "Cách người ngoài hành tinh sinh tồn",
  "Chủ đề: “Nếu loài người biến mất”",
  "Cách xây nhà bằng đá trong rừng 3 ngày",
  "Review sản phẩm bằng nhân vật hoạt hình 3D",
  "Hướng dẫn nấu ăn kiểu anime",
  "Kể chuyện “mẹ dạy con 5 điều” qua hoạt hình",
  "24h sống trong game Minecraft ngoài đời thật",
  "Review đồ công nghệ AI ảo",
  "Điều kỳ lạ xảy ra nếu mặt trời tắt trong 24h",
  "Thử nghiệm: uống nước biển 7 ngày",
  "Tạo thế giới trái ngược: ngày là đêm, đêm là ngày",
  "Người tí hon sống giữa thành phố người khổng lồ",
  "Kịch bản viễn tưởng: Robot nuôi con người",
  "Hướng dẫn tạo ra 1.000 video AI 1 ngày",
  "Sự thật lịch sử bị giấu kín",
  "Thử làm tỷ phú trong thế giới ảo",
  "Bí mật kiến tạo Kim Tự Tháp",
  "Vùng đất phép thuật – cây biết nói",
  "Tập gym trong thế giới AI",
  "Cuộc sống 1 triệu năm sau",
  "Nấu ăn cùng rồng lửa",
  "Làm vlog ở hành tinh sao Hỏa",
  "Nhân vật anime bước ra đời thực",
  "Fashion Show thế kỷ 25",
  "Cuộc sống của các vị thần nếu họ còn sống",
  "Loài vật biết làm nhà chọc trời",
  "Cuộc chiến Team Lửa vs Team Băng",
  "Tái tạo cảnh phim 3D cực chất bằng AI",
  "Cách kiếm 10.000$ từ AI trong 30 ngày",
  "Tạo video giả lập camera CCTV",
  "Ăn theo chủ đề trending Tiktok nhưng làm bằng AI",
  "Review lịch sử chiến tranh qua 3D siêu thực",
  "Hướng dẫn làm video động vật nhảy TikTok",
  "Cách dỗ con nít bằng hoạt hình 3D",
  "Thế giới không trọng lực",
  "Video kịch bản kiểu “Chọn đáp án A/B/C”",
  "Hành tinh có 5 mặt trời",
  "24h sống không công nghệ",
  "“Làm sạch đại dương” thử thách AI mô phỏng",
  "Nhạc AI remix + video hoạt hình lời bài hát",
  "Fan made anime cho người nghèo (bằng AI)",
  "Ô tô biết nói chuyện với chủ nhân",
  "Nhà vô địch boxing ảo chọi nhau",
  "Video kể chuyện nhân quả kiểu Phật giáo",
  "Mở khóa 7 luân xa bằng AI",
  "Song long hợp bích – rồng xanh vs rồng đỏ",
  "Đi xuyên không 1.000 năm gặp chính mình",
  "Video kể chuyện tình yêu thời cổ đại",
  "Cách xây nhà trên cây tự động bằng AI",
  "Bí mật giấc mơ – Khi bạn ngủ, điều gì xảy ra?",
  "Bộ tộc sống trong mây",
  "1.000 năm tiến hóa trong 60 giây",
  "Kể truyện ma phiên bản 3D hoạt hình",
  "Hướng dẫn vẽ tranh ảo phòng khách",
  "Người tí hon sinh tồn trong tủ lạnh",
  "Video về thế giới robot ăn pin",
  "Hướng dẫn tạo ảnh thần tiên, elf, long tóc bồng bềnh",
  "Cách làm truyện cổ tích bằng 50 prompt",
  "10 sự thật bí ẩn dưới lòng đại dương",
  "Review thành phố bị bỏ hoang",
  "Video game sống động, bạn là nhân vật chính",
  "Hướng dẫn đi lại thời gian bằng AI",
  "Giải mã giấc mơ bằng hình ảnh AI",
  "Video “Ai sẽ thắng?” – Sư tử vs Robot",
  "Ở trong sa mạc 7 ngày không nước",
  "Thế giới dưới 100 mét nước",
  "Sáng tạo nhân vật hoạt hình thương hiệu shop",
  "Tạo video vui nhộn cho mèo cưng",
  "Phân tích TikTok viral 100 triệu views trong 1 phút bằng AI"
];
